### ISSUE TITLE
Databricks execution error

### ISSUE THREAD

**Issue by manucorujo** [microsoft/lst-bench#216]
We are trying to execute the benchmark on a Databricks serverless SQL warehouse using the Databricks JDBC connector, and we are facing the following problem:

![databricks](https://github.com/microsoft/lst-bench/assets/63512883/212d868d-ea16-410d-8c7c-518d143a84cd)

The error says that the path does not exist (as we marked with a green arrow), but the other arrow shows that actually it does exist.

We think the problem comes from our configuration of the `experiment_config.yaml` file. The file contains the following parameters:

````yaml
---
version: 1
id: test_1
repetitions: 1

metadata:
  system: spark
  system_version: 3.3.1
  table_format: delta
  table_format_version: 2.2.0
  scale_factor: 1
  mode: cow

parameter_values:
  external_catalog: spark_catalog
  external_database: external_tpcds
  external_table_format: csv
  external_data_path: 'dbfs:/user/hive/warehouse/external_tpcds.db/'
  external_options_suffix: ',header="true"'
  external_tblproperties_suffix: ''
  catalog: spark_catalog
  database: delta_tpcds
  table_format: delta
  scale_factor: 1
  data_path: 'dbfs:/user/hive/warehouse/delta_tpcds.db/'
  options_suffix: ''
  tblproperties_suffix: ''
````

We are completing this file based on the info provided by the [sample_experiment_config.yaml](https://github.com/microsoft/lst-bench/blob/main/src/main/resources/config/spark/sample_experiment_config.yaml) file and the info about the parameters contained in the [experiment_config.json](https://github.com/microsoft/lst-bench/blob/main/src/main/resources/schemas/experiment_config.json) file. One problem is that this json file says what is the metadata param, but not all the subparams that it can contain and all their information.
